language: python
python:
  - "3.6"
before_install:
  - pip install coveralls
install:
  - pip install pipenv
  - pipenv install
script:
  - python -m unittest discover -v
after_success:
    - coveralls
